[package]
name = "first_project"
version = "0.1.0"
authors = ["Jeremy Frank <jfrank@summitinvest.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.7.3"